### PR TITLE
[Proposal] Prefer sbt for Scala projects

### PR DESCRIPTION
**Pull request by guizmaii**
Hi again,

Because in the Scala world, sbt is often prefered. Here's the (not exact) translation of you `pom.xml` to a sbt build.

Because I don't understand everything in the `<build>...</build>` section, I'm not sure if my config here does everything your maven config did.

Also, I don't understand the `<reporting>...</reporting>` part. I don't know what it used for.

The rest is the same.

## Small advices when you develop in a Scala project with sbt:

Never trust Intellij nor any IDE. Always trust `scalac`. 
So, always run a sbt console (`$ sbt`) in which you launch the following command when you're coding `~test:compile`.

The `~` means that It'll watch your files and automatically relaunch the command that follows it when you change a file.
It's very useful because you'll have a very fast feedback loop on your code thanks to this command.

The `test:compile` part of the command says to sbt to compile your code + your tests code.

You can also use `~compile` to only compile your code without the tests code.

Ofc, you can also code with the `~test` command launched in your sbt console. It will relaunch your tests on each file change. It's very useful when your tests are fast. It could be boring when your test suite is big and/or slow.

😉

### CODE REVIEW

**Comment by maxpumperla** [comment]
@guizmaii super cool, thanks. but can we _add_ sbt as another option. I personally prefer maven for my projects. changing travis etc. is fine with me, but please keep the original readme statements and add an sbt section. In fact, put the sbt section first (I know scala guys will like it) and mvn second.

Makes sense? thanks for your addition.

**Comment by maxpumperla** [comment]
hmm, also: are you sure your build picks up the scalafmt propties properly? You have some formatting changes in your PR that get reverted when I build locally.

**Comment by guizmaii** [comment]
IMO, it's not a good idea to have both:
  1. it's more maintenance burden
  2. The scalafmt versions are not the same (I use a more recent one) which brings the differences you observe.

IMO, if you prefer to use maven, I'll close this PR and you just use maven.
If you want to give a chance to sbt, merge this PR and use sbt.

It's your project. You decide, ofc.

**Comment by maxpumperla** [comment]
I like sbt. not sure what the problem is with supporting multiple build tools other than that I have to maintain it. No harm done in having both. I'll merge and add mvn back in later. :/

thanks for this contribution!

**Pull request merged**
